version: "3.7"
services:
  db:
    container_name: holberton_db
    image: mysql:8.0.33-debian
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: holberton
      MYSQL_USER: kalibetre
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./:/tmp/alx
      - holberton_db_data:/var/lib/mysql

volumes:
  holberton_db_data:
